### ISSUE TITLE
Ruby 3.0.0 test fail

### ISSUE THREAD

**Issue by orlando-labs** [ankane/torch.rb#20]
After succeeding the tests on 2.7 branch I found out one test fails on newly released ruby 3.

```
ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

bundle exec rake test
...
Fabulous run in 37.116876s, 8.0826 runs/s, 14.8450 assertions/s.

  1) Error:
TensorIndexingTest#test_getter:
TypeError: no implicit conversion from nil to integer
    /home/slowpilot/torch.rb/lib/torch/tensor.rb:162:in `_index'
    /home/slowpilot/torch.rb/lib/torch/tensor.rb:162:in `[]'
    /home/slowpilot/torch.rb/test/tensor_indexing_test.rb:22:in `test_getter'

300 runs, 551 assertions, 0 failures, 1 errors, 19 skips
```

I'll try to look into this asap.

**Comment by ankane** [comment]
Thanks @orlando-labs, just pushed out a new release with the fix.
