### ISSUE TITLE
Support for Complex numbers

### ISSUE THREAD

**Issue by lfuszara1** [ankane/torch.rb#25]
```
irb(main):001:0> require 'torch.rb'
=> true
irb(main):002:0> Torch.tensor(1+1i)
/home/lukasz/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/torch-rb-0.5.3/lib/torch.rb:401:in `to_f': can't convert 1+1i into Float (RangeError)
	from /home/lukasz/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/torch-rb-0.5.3/lib/torch.rb:401:in `_tensor'
	from /home/lukasz/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/torch-rb-0.5.3/lib/torch.rb:401:in `tensor'
```

libtorch supports complex numbers but torch.rb not.

**Comment by ankane** [comment]
Hey @lfuszara1, added support on master.
